# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:

  node:
    container_name: nodeapp
    image: nodeapp # This is just a radom name (no such predefined image)
    build:
      context: .
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/angular2restfulservice
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network
      
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge